Update `test/config/300-certificate.yaml`
The CI for net-certmanager is broken as https://testgrid.k8s.io/r/knative-own-testgrid/net-certmanager#continuous

It  was caused by old CRD in `test/config/300-certificate.yaml` as:

```
error: unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

This patch changes the `test/config/300-certificate.yaml` to use symlink against networking repo's.